"""empty message

Revision ID: 52569b85afa4
Revises: 
Create Date: 2021-01-07 20:49:30.556174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52569b85afa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_tiles',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tile_count_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['tile_count_id'], ['tile_count.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'tile_count_id')
    )
    op.create_table('board_layout',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('board_state',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('played_tile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['played_tile_id'], ['played_tile.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'played_tile_id')
    )
    op.create_table('dictionary',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('distribution',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'dictionary_id')
    )
    op.create_table('entry',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=30, collation='NOCASE'), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_word'), 'entry', ['word'], unique=True)
    op.create_table('friends',
    sa.Column('my_player_id', sa.Integer(), nullable=False),
    sa.Column('friend_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['my_player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('my_player_id', 'friend_player_id')
    )
    op.create_table('game',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement='ignore_fk', nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('board_layout_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('game_player_to_play_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_layout_id'], ['board_layout.id'], ),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], ),
    sa.ForeignKeyConstraint(['id', 'game_player_to_play_id'], ['game_player.game_id', 'game_player.id'], name='fk_game_player_to_play'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_player',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id')
    )
    op.create_table('modifier',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter_multiplier', sa.Integer(), nullable=False),
    sa.Column('word_multiplier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter_multiplier', 'word_multiplier')
    )
    op.create_table('modifiers',
    sa.Column('board_layout_id', sa.Integer(), nullable=False),
    sa.Column('positioned_modifier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_layout_id'], ['board_layout.id'], ),
    sa.ForeignKeyConstraint(['positioned_modifier_id'], ['positioned_modifier.id'], ),
    sa.PrimaryKeyConstraint('board_layout_id', 'positioned_modifier_id')
    )
    op.create_table('move',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_player_id', sa.Integer(), nullable=False),
    sa.Column('primary_word', sa.String(length=21), nullable=True),
    sa.Column('secondary_words', sa.String(length=462), nullable=True),
    sa.Column('tiles_exchanged', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('played_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_player_id'], ['game_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('played_tile',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile_id', 'row', 'column')
    )
    op.create_table('player',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=15), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('highest_individual_score', sa.Integer(), nullable=False),
    sa.Column('highest_combined_score', sa.Integer(), nullable=False),
    sa.Column('best_word_score', sa.Integer(), nullable=False),
    sa.Column('friend_key', sa.String(length=15), nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('board_layout_id', sa.Integer(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_layout_id'], ['board_layout.id'], ),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], ),
    sa.ForeignKeyConstraint(['distribution_id'], ['distribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positioned_modifier',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row', 'column', 'modifier_id')
    )
    op.create_table('rack',
    sa.Column('game_player_id', sa.Integer(), nullable=False),
    sa.Column('tile_count_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_player_id'], ['game_player.id'], ),
    sa.ForeignKeyConstraint(['tile_count_id'], ['tile_count.id'], ),
    sa.PrimaryKeyConstraint('game_player_id', 'tile_count_id')
    )
    op.create_table('role',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tile',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('letter', sa.String(length=1, collation='NOCASE'), nullable=True),
    sa.Column('is_blank', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter', 'is_blank', 'value')
    )
    op.create_table('tile_count',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile_id', 'count')
    )
    op.create_table('tile_distribution',
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('tile_count_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distribution.id'], ),
    sa.ForeignKeyConstraint(['tile_count_id'], ['tile_count.id'], ),
    sa.PrimaryKeyConstraint('distribution_id', 'tile_count_id')
    )
    op.create_table('user',
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=255, collation='NOCASE'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('user')
    op.drop_table('tile_distribution')
    op.drop_table('tile_count')
    op.drop_table('tile')
    op.drop_table('role')
    op.drop_table('rack')
    op.drop_table('positioned_modifier')
    op.drop_table('player')
    op.drop_table('played_tile')
    op.drop_table('move')
    op.drop_table('modifiers')
    op.drop_table('modifier')
    op.drop_table('game_player')
    op.drop_table('game')
    op.drop_table('friends')
    op.drop_index(op.f('ix_entry_word'), table_name='entry')
    op.drop_table('entry')
    op.drop_table('entries')
    op.drop_table('distribution')
    op.drop_table('dictionary')
    op.drop_table('board_state')
    op.drop_table('board_layout')
    op.drop_table('bag_tiles')
    # ### end Alembic commands ###
