"""
Data migration to initialize the tiles and tile counts needed.

Revision ID: b3069b0347d5
Revises: 3ea1bfba1ae7
Create Date: 2020-06-14 18:40:13.666551

"""
import os
import sys

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

sys.path.append(os.getcwd())
from slobsterble.constants import DISTRIBUTION, TILE_VALUES
from slobsterble.models import Tile, TileCount

# revision identifiers, used by Alembic.
revision = 'b3069b0347d5'
down_revision = '3ea1bfba1ae7'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for letter, value in TILE_VALUES.items():
        is_blank = letter is None
        tile = Tile(letter=letter, is_blank=is_blank, value=value)
        if session.query(Tile).filter_by(
                letter=tile.letter, is_blank=tile.is_blank,
                value=tile.value).first() is None:
            session.add(tile)
        for frequency in range(1, DISTRIBUTION[letter] + 1):
            tile_count = TileCount(tile=tile, count=frequency)
            if session.query(TileCount).filter_by(
                    tile_id=tile.id, count=frequency).first() is None:
                session.add(tile_count)
    for offset in range(26):
        letter = chr(ord('A') + offset)
        tile = Tile(letter=letter, is_blank=True, value=0)
        if session.query(Tile).filter_by(
                letter=tile.letter, is_blank=tile.is_blank,
                value=tile.value).first() is None:
            session.add(tile)
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
