"""empty message

Revision ID: e4c41fcd1373
Revises: b3069b0347d5
Create Date: 2020-12-28 12:46:14.560513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c41fcd1373'
down_revision = 'b3069b0347d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('friend_key', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'friend_key')
    # ### end Alembic commands ###
